proxies:
  - name: Tencent Serve
    type: vmess
    server: 124.222.42.58
    port: 6688
    uuid: 8c042a38-71c1-1dcb-00df-54880236e0dc
    alterId: 0
    cipher: auto
    udp: true
    skip-cert-verify: false
    tls: false
proxy-groups:
  - name: Default
    type: url-test
    proxies:
      - Tencent Serve
    url: https://www.bilibili.com
    interval: "600"
    tolerance: "150"
  - name: Proxy ReturnChina🌏
    type: select
    proxies:
      - Default
      - DIRECT
      - Tencent Serve
  - name: Others
    type: select
    proxies:
      - Proxy ReturnChina🌏
      - DIRECT
rules:
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - RULE-SET,ChinaDomain,Proxy ReturnChina🌏
  - RULE-SET,ChinaIp(By ACL4SSR),Proxy ReturnChina🌏
  - RULE-SET,Bilibili(By ACL4SSR),Proxy ReturnChina🌏
  - RULE-SET,ChinaMediaStream(by Blackccold),Proxy ReturnChina🌏  
  - GEOIP,CN,Proxy ReturnChina🌏
  - MATCH,Others
dns:
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
    - 192.168.1.1
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://dns.cloudflare.com/dns-query
    - "[2001:da8::666]:53"
    - https://public.dns.iij.jp/dns-query
    - https://jp.tiar.app/dns-query
    - https://jp.tiarap.org/dns-query
    - tls://dot.tiar.app
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
    - +.*
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
    - 223.5.5.5
    - 192.168.1.1
    - "[2001:da8::666]:53"
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: "123456"
bind-address: "*"
ipv6: false
tun:
  enable: true
  stack: system
  dns-hijack:
    - tcp://8.8.8.8:53
    - tcp://8.8.4.4:53
profile:
  store-selected: true
  store-fake-ip: true
rule-providers:
  ChinaDomain:
    type: http
    behavior: classical
    path: /etc/openclash/rule_provider/ChinaDomain.yaml
    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ChinaDomain.yaml
    interval: 86400
  ChinaIp(By ACL4SSR):
    type: http
    behavior: ipcidr
    path: /etc/openclash/rule_provider/ChinaIp-ACL4SSR.yaml
    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ChinaIp.yaml
    interval: 86400
  Bilibili(By ACL4SSR):
    type: http
    behavior: classical
    path: /etc/openclash/rule_provider/Bilibili-ACL4SSR.yaml
    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/Bilibili.yaml
    interval: 86400
  #China(by ConnorsHua):
    #type: http
    #behavior: classical
    #path: /etc/openclash/rule_provider/China.yaml
    #url: https://github.com/blackkcold/Profiles/raw/master/Clash/RuleSet/China.yaml
    #interval: 86400
  ChinaMediaStream(by Blackccold):
    type: http
    behavior: classical
    path: /etc/openclash/rule_provider/ChinaMediaStream.yaml
    url: https://github.com/blackkcold/Stock-of-Clash-Config/raw/main/ChinaMediaStream.yaml
    interval: 86400